name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17', '21', '23']
        nextflow: ['latest-stable' ]
        nxf_syntax_version: ['v1', 'v2']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Setup Nextflow ${{ matrix.nextflow }}
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.nextflow }}"

      - name: Test
        run: NXF_SYNTAX_PARSER=${{ matrix.nxf_syntax_version }} mvn install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
